name: Build

on: [ push ]

jobs:
  lint_and_format:
    name: Lint and format checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Ruff lint
        uses: astral-sh/ruff-action@v3
        with:
          args: check --select I --output-format=github

      - name: Ruff format
        uses: astral-sh/ruff-action@v3
        with:
          args: format --check
